"""
generate_pdf.py
---------------
Generates a formatted PDF student report using reportlab.

Inputs:
  - stats:       dict from calculate_stats.build_full_stats()
  - chart_paths: dict from generate_charts.generate_all_charts()

Output:
  - PDF file saved to .tmp/reports/<roll_no>_report.pdf
  - Returns the path to the PDF
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


REPORT_DIR = ".tmp/reports"


def _ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def generate_pdf(stats: dict, chart_paths: dict) -> str:
    """
    Build a PDF report.

    Args:
        stats:       Full stats dict (student + attendance + tests + exams)
        chart_paths: {"attendance": "path.png", "tests": "path.png", "exams": "path.png"}

    Returns:
        Absolute (or relative) path to the generated PDF.
    """
    _ensure_dir(REPORT_DIR)
    roll_no = stats["student"]["roll_no"]
    out_path = os.path.join(REPORT_DIR, f"{roll_no}_report.pdf")

    doc = SimpleDocTemplate(
        out_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # ── Custom styles ────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1A237E"),
        spaceAfter=4,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#546E7A"),
        spaceAfter=12,
        alignment=TA_CENTER,
    )
    section_header_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1A237E"),
        spaceBefore=14,
        spaceAfter=6,
        borderPad=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#212121"),
        spaceAfter=4,
    )

    # ── Story (list of flowables) ────────────────────────────────────────────
    story = []

    # Title
    story.append(Paragraph("📋 Student Academic Report", title_style))
    story.append(Paragraph("Generated by WhatsApp Bot System", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2,
                             color=colors.HexColor("#1A237E"), spaceAfter=14))

    # Student Info Table
    student = stats["student"]
    info_data = [
        ["Field", "Value"],
        ["Name", student.get("name", "—")],
        ["Class", student.get("class", "—")],
        ["Roll No", student.get("roll_no", "—")],
    ]
    info_table = Table(info_data, colWidths=[5 * cm, 11 * cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A237E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.HexColor("#E8EAF6"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C5CAE9")),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Section: Attendance ──────────────────────────────────────────────────
    att = stats["attendance"]
    story.append(Paragraph("📅 Attendance Summary", section_header_style))
    att_data = [
        ["Total Days", "Present", "Absent", "Attendance %"],
        [
            str(att["total"]),
            str(att["present"]),
            str(att["absent"]),
            f"{att['percentage']}%",
        ],
    ]
    att_table = Table(att_data, colWidths=[4 * cm] * 4)
    _apply_stat_table_style(att_table, low_warn=att["percentage"] < 75)
    story.append(att_table)
    story.append(Spacer(1, 0.3 * cm))

    if att["percentage"] < 75:
        story.append(
            Paragraph(
                "⚠️ <b>Warning:</b> Attendance is below the 75% threshold.",
                ParagraphStyle("Warn", parent=body_style,
                               textColor=colors.HexColor("#C62828")),
            )
        )
    story.append(Spacer(1, 0.3 * cm))

    # Attendance chart
    _add_chart(story, chart_paths.get("attendance"), "Attendance Trend")

    # ── Section: Tests ───────────────────────────────────────────────────────
    tests = stats["tests"]
    story.append(Paragraph("📝 Test Performance", section_header_style))
    story.append(
        Paragraph(
            f"Overall Test Average: <b>{tests['average']}</b>", body_style
        )
    )
    if tests["by_subject"]:
        sub_data = [["Subject", "Average Marks"]]
        for subj, avg in tests["by_subject"].items():
            sub_data.append([subj, str(avg)])
        sub_table = Table(sub_data, colWidths=[8 * cm, 8 * cm])
        _apply_generic_table_style(sub_table)
        story.append(sub_table)
    story.append(Spacer(1, 0.3 * cm))
    _add_chart(story, chart_paths.get("tests"), "Test Marks Trend")

    # ── Section: Exams ───────────────────────────────────────────────────────
    exams = stats["exams"]
    story.append(Paragraph("🎓 Exam Performance", section_header_style))
    story.append(
        Paragraph(
            f"Overall Exam Average: <b>{exams['average']}</b>", body_style
        )
    )
    if exams["by_subject"]:
        exam_data = [["Subject", "Average Marks"]]
        for subj, avg in exams["by_subject"].items():
            exam_data.append([subj, str(avg)])
        exam_table = Table(exam_data, colWidths=[8 * cm, 8 * cm])
        _apply_generic_table_style(exam_table)
        story.append(exam_table)
    story.append(Spacer(1, 0.3 * cm))
    _add_chart(story, chart_paths.get("exams"), "Exam Marks by Subject")

    # Footer note
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=1,
                             color=colors.HexColor("#C5CAE9"), spaceAfter=6))
    story.append(
        Paragraph(
            "This report was auto-generated. For queries, contact the school administration.",
            ParagraphStyle("Footer", parent=body_style,
                           textColor=colors.grey, fontSize=8, alignment=TA_CENTER),
        )
    )

    doc.build(story)
    return out_path


# ── helpers ──────────────────────────────────────────────────────────────────

def _add_chart(story, path: str, title: str):
    if path and os.path.exists(path):
        story.append(Image(path, width=15 * cm, height=7.5 * cm))
    else:
        story.append(
            Paragraph(f"[Chart not available: {title}]",
                      getSampleStyleSheet()["Italic"])
        )
    story.append(Spacer(1, 0.4 * cm))


def _apply_stat_table_style(table, low_warn=False):
    header_color = colors.HexColor("#C62828") if low_warn else colors.HexColor("#1A237E")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.HexColor("#E8EAF6"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C5CAE9")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))


def _apply_generic_table_style(table):
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A237E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.HexColor("#E8EAF6"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C5CAE9")),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))


# ── quick test ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    from calculate_stats import build_full_stats
    from generate_charts import generate_all_charts

    sample = {
        "student": {"roll_no": "23", "name": "Rahul", "class": "10A"},
        "attendance": [
            {"date": "2024-01-01", "status": "Present"},
            {"date": "2024-01-02", "status": "Absent"},
            {"date": "2024-01-03", "status": "Present"},
            {"date": "2024-01-04", "status": "Present"},
            {"date": "2024-01-05", "status": "Present"},
        ],
        "tests": [
            {"date": "2024-01-10", "subject": "Maths", "marks": 82},
            {"date": "2024-01-11", "subject": "Science", "marks": 76},
            {"date": "2024-02-10", "subject": "Maths", "marks": 90},
        ],
        "exams": [
            {"date": "2024-03-01", "subject": "Maths", "marks": 88},
            {"date": "2024-03-02", "subject": "Science", "marks": 74},
            {"date": "2024-03-03", "subject": "English", "marks": 91},
        ],
    }

    stats = build_full_stats(sample)
    chart_paths = generate_all_charts(stats)
    pdf_path = generate_pdf(stats, chart_paths)
    print(f"PDF generated: {pdf_path}")
